variables:
- group: ServiceConnections
- name: azureSubscription
  value: $(ServiceConnectionPRD1)
- name: docker.imageName
  value: 'webapigateway'
- name: acr.azureContainerRegistryName
  value: 'prdrwdinfac1401'
- name: acr.repositoryName
  value: 'apiwebrepository'
- name: serviceName
  value: 'prdrwdwebwa1409'
